name: Publish Packege

on:
  release:
    types:
      - published
jobs:
  run_tests:
    name: Run Tests
    uses: ./.github/workflows/tests.template.yml
    with:
      dotnet_version: '9.0.x'
      configuration: 'Release'
      solution_name: 'Bytegix.Lib.ResultHandling.sln'
      
  create_nuget:
    name: Create NuGet Package
    uses: ./.github/workflows/create-nuget.template.yml
    with:
      dotnet_version: '9.0.x'
      nuget_directory: nuget
      configuration: 'Release'
      solution_name: 'Bytegix.Lib.ResultHandling.sln'

  publish_nuget:
    name: Publish NuGet Package
    uses: ./.github/workflows/publish-nuget.template.yml
    needs: [ create_nuget, run_tests ]
    with:
      dotnet_version: '9.0.x'
      nuget_source: 'https://api.nuget.org/v3/index.json'
      nuget_directory: nuget
    secrets:
      nuget_auth_token: ${{ secrets.NUGET_API_KEY }}