name: tests-template

on:
  workflow_call:
    inputs:
      configuration:
        required: false
        type: string
        default: Release
      dotnet_version:
        required: false
        type: string
        default: '9.0.x'
      solution_name:
        required: true
        type: string
        description: 'The name of the solution file to be used for testing'

jobs:
  run_tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Remove existing NuGet config
        run: rm -f ${{ github.workspace }}/nuget.config
      - name: Setup .NET ${{ inputs.dotnet_version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ${{ env.NUGET_PACKAGES }}
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nuget-${{ runner.os }}
            nuget
      - name: Restore NuGet packages
        run: dotnet restore ${{ inputs.solution_name }}
      - name: Build solution
        run: dotnet build ${{ inputs.solution_name }} --configuration Release --no-restore
      - name: Run unit tests with code coverage
        run: dotnet test ${{ inputs.solution_name }} --configuration Release --no-build --collect "Code Coverage"